# Site settings
title: Computer Networking
email: bmiller@luther.edu
description: "Notes and Syllabus for Internet Programming"
baseurl: "http://bnmnetp.github.io/CS341/"
url: "http://bnmnetp.github.io"
twitter_username: bnmnetp
github_username:  bnmnetp

# Build settings
permalink: pretty
