# Site settings
title: Internet Programming
email: bmiller@luther.edu
description: "Notes and Syllabus for Internet Programming"
baseurl: "http://bnmnetp.github.io/CS365/"
url: "http://reputablejournal.com"
twitter_username: bnmnetp
github_username:  bnmnetp

# Build settings
permalink: pretty
